version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  main:
    jobs:
      - build-test-linting
      - containerization:
          requires:
            - build-test-linting
          filters:
            branches:
              only: main


jobs:
  build-test-linting:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run linting
          command: flake8
  containerization:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - setup_remote_docker
      # build and push Docker image
      - run: |
          docker build -t yoanberchel/orange-county-lettings:$CIRCLE_SHA1 .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push yoanberchel/orange-county-lettings:$CIRCLE_SHA1