version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  main:
    jobs:
      - build-test-linting
      - containerization:
          requires:
            - build-test-linting
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - containerization
          filters:
            branches:
              only: main


jobs:
  build-test-linting:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run linting
          command: flake8
  containerization:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image to DockerHub
          command: |
            docker build -t usertest1111/oc-lettings:$CIRCLE_SHA1 .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push usertest1111/oc-lettings:$CIRCLE_SHA1
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build, push and deploy Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a test-oc web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a test-oc web