version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  main:
    jobs:
      - build-test-linting


jobs:
  build-test-linting:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run linting
          command: flake8
